### ISSUE TITLE
请问有数据接口说明吗？

### ISSUE THREAD

**Issue by markqiu** [cao6237699/paper_trading#1]
比如order类的各个字段的含义

**Comment by cao6237699** [comment]
> 比如order类的各个字段的含义

你好，在ReadMe里面我没有添加接收说明，在例如order类定义中有一些说明的，但是不全。有一些可以通过字段名大概理解。
我会在下一个版本中补充详细接口说明。
谢谢关注

**Comment by markqiu** [comment]
简单使用了你的项目，感觉设计的不错。我也在开发类似的东西，咱们可以合作

**Comment by cao6237699** [comment]
谢谢关注，如果可以的话合作是双赢。
不过我不清楚你在开发什么项目，有个小建议，就是现在主流的共享平台上找找类似的项目，如果差不多，在那个基础上开发可能更好些。我当时之所以开这个项目，起因就是主流平台上没有类似项目。相近的几个项目都无法在A股上使用，并且不符合国人的使用习惯。然后自己在做量化的时候确实有这方面的痛点。所以才开发的。

**Comment by markqiu** [comment]
我做的就是类似你现在这个项目啊，我也是因为找了一圈没有合适的，想自己开发一个模拟交易的，呵呵

**Comment by markqiu** [comment]
我的项目也传上去了，有兴趣一起搞搞吗？我在项目里面引用了很多你的代码
@cao6237699

**Comment by cao6237699** [comment]
@markqiu 好，有时间可以一起。

**Comment by markqiu** [comment]
太好了，你有时间可以看一下我们的项目markqiu/paperplane

**Comment by markqiu** [comment]
我已提交文档
