### ISSUE TITLE
交易完后账户记录数据的市值没有变化，盈亏均为初始资产

### ISSUE THREAD

**Issue by markqiu** [cao6237699/paper_trading#4]

**Comment by cao6237699** [comment]
> _No description provided._

你用的是最新的版本吗？我目前模拟盘和回测都没有发现类似情况。如果是查看账户记录的话，实盘必须让系统完成清算，模拟盘必须手工清算。

**Comment by markqiu** [comment]
是每次买卖都需要调用清算接口是吗？我们好像也发现了这个问题，但这个设计好像有点不合理呀。

**Comment by cao6237699** [comment]
> 是每次买卖都需要调用清算接口是吗？我们好像也发现了这个问题，但这个设计好像有点不合理呀。

这样的设计是参照中国登记结算公司实际情况。之所以要有清算，举一个简单的例子：像T+1这种交易制度，T日买入的股票，T+1才能卖出。所以在T日完成后市场要进行一次清算，模拟完成资金的结算、市值的计算及股份的交割；
在使用过程中
模拟盘交易无论是手工交易还是程序化交易，如果市场正常关闭，是会在关闭前自动进行清算的。
如果是用于回测，那么必须要参照同样的规则手工去调用清算接口。这样市场的通用性就提高了。

**Comment by markqiu** [comment]
ok ok
