### ISSUE TITLE
请问能否支持场内基金？

### ISSUE THREAD

**Issue by markqiu** [cao6237699/paper_trading#5]

**Comment by cao6237699** [comment]
理论上，我的想法是一个模拟交易的框架，任何想模拟交易的都可以在这个框架里面实现，而且只需要简单的代码就可以，例如接收订单的方法，和核心撮合的方法，其他的只要继承自市场类就可以了，当然目前框架做的不是很完善，自己使用起来效率也比较低。

**Comment by markqiu** [comment]
想法挺好的，没事，我们一起来努力把它变好
